name: bitbithabit
description: A new Flutter project for final exam.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.7.2' # Gunakan SDK Dart 3 terbaru

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Local Storage (Database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  uuid: ^4.5.1
  collection: ^1.19.1
  
  # Navigation
  go_router: ^14.1.0
  
  # Utility & UI
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generators
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true